//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by COGMAP.RC
//
#define IDR_MAINFRAME                   2
#define IDR_COGMAPTYPE                  3
#define IDD_ABOUTBOX                    100
#define IDP_BUSY                        100
#define IDD_SHOW_MAP                    101
#define IDC_LIST1                       101
#define IDD_DO_TRIALS                   102
#define IDC_RESP_LIST                   102
#define IDC_CHOICE_1                    103
#define IDD_INFODLG                     103
#define IDC_CHOICE2                     104
#define IDC_CHOICE3                     105
#define IDC_WORD3                       107
#define IDC_WORD2                       108
#define IDC_WORD1                       109
#define IDC_WORD_LIST                   110
#define IDC_ITEM_NUM                    111
#define IDC_RESP_NUM                    112
#define IDM_VIEW_TRIAD                  32768
#define ID_VIEW_TRIAD                   32769
#define ID_NAT_INSERT_NEW               32770
#define ID_INSERT_WORD                  32771
#define ID_INSERT_TXTR                  32772
#define ID_INSERT_CA1D                  32773
#define ID_VIEW_INFO                    32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         112
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
