//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by REFMAP.RC
//
#define IDR_MAINFRAME                   2
#define IDR_REFMAPTYPE                  3
#define IDD_ABOUTBOX                    100
#define IDP_BUSY                        100
#define IDD_REF_FORM                    101
#define IDC_UNIQUE_ID                   101
#define IDC_TITLE                       102
#define IDD_REF_DLG                     102
#define IDC_AUTHORS                     103
#define IDC_INSTITUTION                 104
#define IDC_SOURCE                      105
#define IDC_MeSH                        109
#define IDC_ABSTRACT                    110
#define ID_VIEW_MAP                     32768
#define ID_REF_ADD                      32769
#define ID_REF_DEL                      32770
#define IF_FILE_IMPORT                  32771
#define ID_FILE_IMPORT_CIT              32772
#define ID_REF_SORT                     32773
#define ID_REF_SWAP                     32774
#define ID_FILE_IMPORT_HTML             32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         111
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
