//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by PSIPHYS.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define ID_FILE_COMP                    32768

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         32769
#define _APS_NEXT_CONTROL_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
