ECHO OFF
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
ECHO $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
CLS
ECHO                 ***** Welcome to the Collar 1.0 *****
ECHO                 ******** Pretty simple, eh? *********
ECHO                 *************************************
ECHO                   Well, only YOU can make it better!
ECHO                 *************************************
ECHO                    *******************************
ECHO                       *************************
ECHO                          *******************
ECHO                             *************
ECHO                                *******
ECHO                                   *
ECHO <<< TRIO Project >>>
ECHO 1) Change the header
ECHO 2) Delete finished items from this list
ECHO 3) Add new items to this list
ECHO 4) Move MSBACKUP files to PKZIP format archives
ECHO 5) Print out all PKZIP and flat archives
ECHO 6) Install TC
ECHO 7) Finish Debrecht's modifications (BACKUP, RESTORE, NEWYEAR)
ECHO 8) Set goals for Q1 1995; Jan 1995; W2 Jan 1995
ECHO 9) Store old copies of COLLAR.BAT in usr\dgl\collar\archive
ECHO <<< washu >>>
ECHO 10) Outline reading list and schedule for WS95
ECHO 11) Outline project for CNS
ECHO 12) Set goals for Q1 1995; Jan 1995; W2 Jan 1995
ECHO <<< Eevorg project >>>
ECHO 13) List possible goodies to sell to TRIO Collar
ECHO 14) Set goals for Q1 1995; Jan 1995; W2 Jan 1995
PAUSE
CLS
ECHO (((((((. .))))))))))))))))))))))))))))))))))))))))))))))))))))
ECHO         O
ECHO      ^     ^
ECHO <<< TRIO Project >>>
ECHO ALSO, DON'T FORGET TO:
ECHO     Write a COLLAR program in TC that monitors its own on time
ECHO     Then, you can add parameterized goodies for it to try!
ECHO .
ECHO Well, don't just sit there. GET TO IT!
