/* resource.h : Defines the resource constants for the Trio application.
*/

#define IDM_PRINT	    101
#define IDM_EXIT	    102

#define IDM_BROWSE_CONTACTS 111
#define IDM_BROWSE_MESSAGES 112
#define IDM_BROWSE_THREADS  113
#define IDM_NEW_CONTACT     114
#define IDM_EDIT_CONTACT    115

#define IDM_BROWSE_PROJECTS 121
#define IDM_BROWSE_TASKS    122
#define IDM_NEW_PROJECT     123
#define IDM_EDIT_PROJECT    124

#define IDM_RECEIVABLES     131
#define IDM_PAYABLES	    132
#define IDM_LEDGER	    133
#define IDM_CHECKING	    134
#define IDM_SAVINGS	    135

#define IDM_CASCADE	    141
#define IDM_TILE	    142
#define IDM_ARRANGE	    143
#define IDM_CLOSE	    144

#define IDM_ABOUT	    150
