// resource.h : Defines the resource constants for the application.
//
// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (C) 1992 Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and Microsoft
// QuickHelp documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.

#define IDM_NEW     101
#define IDM_OPEN    102
#define IDM_SAVE    103
#define IDM_SAVEAS  104
#define IDM_CLOSE   105
#define IDM_PRINT   106
#define IDM_EXIT    107

#define IDM_ADD     108
#define IDM_DELETE  109
#define IDM_FIND    110
#define IDM_FINDALL 111
#define IDM_EDIT    112

#define IDM_HELP    113
#define IDM_ABOUT   100

#define IDC_DATA    115

#define IDM_TR_ADD	120
#define IDM_TR_VIEW	121
#define IDM_DE_ADD	122
#define IDM_DE_VIEW	123
#define IDM_FP_ADD	124
#define IDM_FP_VIEW	125

#define	IDM_IA_ADD	130
#define	IDM_IA_VIEW	131

#define	IDM_DR_ADD	140
#define	IDM_DR_VIEW	141

#define	IDM_AP_ADD_CHG	150
#define	IDM_AP_ADD_PAY	151
#define IDM_AP_ADD_ACCT 152
#define	IDM_AP_VIEW	153

#define	IDM_AR_ADD_CHG	160
#define	IDM_AR_ADD_PAY	161
#define IDM_AR_BILLS	162
#define IDM_AR_ADD_ACCT 163
#define	IDM_AR_VIEW	164

#define IDC_STATICLASTNAME  200
#define IDC_LASTNAME        300
#define IDC_STATICFIRSTNAME 201
#define IDC_FIRSTNAME       301
#define IDC_STATICPHONE     202
#define IDC_PHONE           302
#define IDC_STATICMOD       203
#define IDC_MOD             303
#define IDC_TICKETNUM               310
#define IDC_LABEL_NAME              402
#define IDC_LABEL_ADDRESS           403
#define IDC_ADDRESS1                404
#define IDC_ADDRESS2                405
