MODULE ListModule;

IMPORT ASCII,Break,CardinalIO,Conversions,Debug,Decimals,Devices,
  Directories,DiskDirectory,DiskFiles,Display,DOS3,DOS31,ErrorCode,
  FileMessage,FileNames,FileSystem,InOut,Keyboard,LogiMouse,MathLib0,
  Mouse,NumberConversion,Options,Processes,ProgMessage,Program,
  RealConversions,RealInOut,RS232Code,RS232Int,RS232Polling,Storage,
  Strings,SYSTEM,System,Termbase,Terminal,TimeDate;

BEGIN
END ListModule.