1. Take the program disk (the one that goes in the left drive) and
   take off the piece of tape covering the notch on the right edge.

               ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
               ³ ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÚ´ /_____ This tape
               ³ ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÀ´ \      right here.
               ³                  ³
               ³                  ³
               ³                  ³
               ³                  ³
               ³                  ³
               ³                  ³
               ÀÄÄÄÄÄÄÄ^ÄÄ^ÄÄÄÄÄÄÄÙ

2. Put the program disk in the right drive and put this disk in the
   left drive.

3. Turn on the computer.

4. When the screen says ALL DONE take the disks out.  Put this new
   piece of tape over the notch on your program disk, and your ready
   to go.